# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_view(object):
    def setupUi(self, main_view):
        main_view.setObjectName("main_view")
        main_view.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(main_view)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(5, 50, 790, 510))
        self.textEdit.setObjectName("textEdit")
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(113, 10, 101, 31))
        self.btnClear.setObjectName("btnClear")
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(5, 10, 101, 31))
        self.btnStart.setObjectName("btnStart")
        main_view.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_view)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        main_view.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_view)
        self.statusbar.setEnabled(False)
        self.statusbar.setObjectName("statusbar")
        main_view.setStatusBar(self.statusbar)

        self.retranslateUi(main_view)
        QtCore.QMetaObject.connectSlotsByName(main_view)

    def retranslateUi(self, main_view):
        _translate = QtCore.QCoreApplication.translate
        main_view.setWindowTitle(_translate("main_view", "Go4Auto-自动指令工具"))
        self.btnClear.setText(_translate("main_view", "清除数据"))
        self.btnStart.setText(_translate("main_view", "开始"))
